<template>
   <div class="loadingio-spinner-spin-7s9mkhiv14w">
    <div class="ldio-sdhr0o015">
      <div><div></div></div>
      <div><div></div></div>
      <div><div></div></div>
      <div><div></div></div>
      <div><div></div></div>
      <div><div></div></div>
    </div>
  </div>
  </template>
  
  <style scoped type="text/css">
 
@keyframes ldio-sdhr0o015 {
  0% {
    opacity: 1;
    backface-visibility: hidden;
    transform: translateZ(0) scale(1.73,1.73);
  } 100% {
    opacity: 0;
    backface-visibility: hidden;
    transform: translateZ(0) scale(1,1);
  }
}
.ldio-sdhr0o015 div > div {
  position: absolute;
  width: 14px;
  height: 14px;
  border-radius: 50%;
  background: #ebb77f;
  animation: ldio-sdhr0o015 2s linear infinite;
}.ldio-sdhr0o015 div:nth-child(1) > div {
  left: 74px;
  top: 44px;
  animation-delay: -1.6666666666666667s;
}
.ldio-sdhr0o015 > div:nth-child(1) {
  transform: rotate(0deg);
  transform-origin: 80px 50px;
}.ldio-sdhr0o015 div:nth-child(2) > div {
  left: 59px;
  top: 70px;
  animation-delay: -1.3333333333333333s;
}
.ldio-sdhr0o015 > div:nth-child(2) {
  transform: rotate(60deg);
  transform-origin: 65px 76px;
}.ldio-sdhr0o015 div:nth-child(3) > div {
  left: 29px;
  top: 70px;
  animation-delay: -1s;
}
.ldio-sdhr0o015 > div:nth-child(3) {
  transform: rotate(120deg);
  transform-origin: 35px 76px;
}.ldio-sdhr0o015 div:nth-child(4) > div {
  left: 14px;
  top: 44px;
  animation-delay: -0.6666666666666666s;
}
.ldio-sdhr0o015 > div:nth-child(4) {
  transform: rotate(180deg);
  transform-origin: 20px 50px;
}.ldio-sdhr0o015 div:nth-child(5) > div {
  left: 29px;
  top: 18px;
  animation-delay: -0.3333333333333333s;
}
.ldio-sdhr0o015 > div:nth-child(5) {
  transform: rotate(240deg);
  transform-origin: 35px 24px;
}.ldio-sdhr0o015 div:nth-child(6) > div {
  left: 59px;
  top: 18px;
  animation-delay: 0s;
}
.ldio-sdhr0o015 > div:nth-child(6) {
  transform: rotate(300deg);
  transform-origin: 65px 24px;
}
.loadingio-spinner-spin-7s9mkhiv14w {
  width: 64px;
  height: 64px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff00;
}
.ldio-sdhr0o015 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.64);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-sdhr0o015 div { box-sizing: content-box; }
/* generated by https://loading.io/ */
  </style>
  